//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_application()
        {
            this.tbl_student = new HashSet<tbl_student>();
        }
    
        public int ap_applicationid { get; set; }
        public string ap_internshiptype { get; set; }
        public string ap_companyname { get; set; }
        public string ap_companyaddress { get; set; }
        public string ap_companyphonenumber { get; set; }
        public string ap_companymail { get; set; }
        public System.DateTime ap_startingdate { get; set; }
        public System.DateTime ap_enddate { get; set; }
        public byte ap_workingday { get; set; }
        public byte[] ap_documentbycompany { get; set; }
        public string ap_managername { get; set; }
        public string ap_managerlastname { get; set; }
        public string ap_managermail { get; set; }
        public string ap_managertitle { get; set; }
        public Nullable<bool> ap_status { get; set; }
        public Nullable<int> ap_studentdepartment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student> tbl_student { get; set; }
    }
}
