//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_internship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_internship()
        {
            this.tbl_student = new HashSet<tbl_student>();
            this.tbl_student1 = new HashSet<tbl_student>();
            this.tbl_report = new HashSet<tbl_report>();
        }
    
        public int i_internshipid { get; set; }
        public string i_internshiptype { get; set; }
        public string i_companyname { get; set; }
        public string i_companyaddress { get; set; }
        public string i_companyphonenumber { get; set; }
        public string i_companymail { get; set; }
        public System.DateTime i_startingdate { get; set; }
        public System.DateTime i_enddate { get; set; }
        public byte i_workingday { get; set; }
        public byte[] i_documentbycompany { get; set; }
        public string i_managername { get; set; }
        public string i_managerlastname { get; set; }
        public string i_managermail { get; set; }
        public string i_managertitle { get; set; }
        public Nullable<int> i_studentdepartment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student> tbl_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student> tbl_student1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_report> tbl_report { get; set; }
    }
}
