//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_report
    {
        public int r_id { get; set; }
        public string r_studennumber { get; set; }
        public string r_reportloc { get; set; }
        public Nullable<System.DateTime> r_date { get; set; }
        public Nullable<int> r_internshipid { get; set; }
        public Nullable<int> r_departmentid { get; set; }
    
        public virtual tbl_report tbl_report1 { get; set; }
        public virtual tbl_report tbl_report2 { get; set; }
        public virtual tbl_internship tbl_internship { get; set; }
    }
}
